### ISSUE TITLE
文件管理器打开报错

### ISSUE THREAD

**Issue by Jousimies** [emacs-eaf/eaf-file-manager#25]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
Traceback (most recent call last):
  File "/home/dn/MyEmacs/site-lisp/packages/emacs-application-framework/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/usr/share/emacs/MyEmacs/site-lisp/packages/emacs-application-framework/eaf.py", line 170, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/usr/share/emacs/MyEmacs/site-lisp/packages/emacs-application-framework/eaf.py", line 187, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/usr/share/emacs/MyEmacs/site-lisp/packages/emacs-application-framework/app/file-manager/buffer.py", line 47, in __init__
    self.load_index_html(__file__)
  File "/home/dn/MyEmacs/site-lisp/packages/emacs-application-framework/core/webengine.py", line 1334, in load_index_html
    with open(self.index_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/emacs/MyEmacs/site-lisp/packages/emacs-application-framework/app/file-manager/dist/index.html'

Process *eaf* aborted (core dumped)
**Describe the bug**

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
下载EAF脚本后要在 emacs-application-framework 目录下运行 install-eaf.py, 更新后也要运行一次 install-eaf.py

**Comment by Jousimies** [comment]
运行了install-eaf.py，没解决问题。

删了重新装就好了。
